platform :ios, '9.0'

inhibit_all_warnings!

target 'EventTime' do
  use_frameworks!

	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'GoogleSignIn'
	pod 'Firebase/Auth'

  # Pods for EventTime

end
